spring:
  application:
    name: resona-backend

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  config:
    import: optional:env[.env]

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:true}   # 필요 시 프로필에서 덮어쓰기

jwt:
  secret: ${SECRET_KEY}
  access-token-expiration: 1800000      # 30분
  refresh-token-expiration: 1209600000  # 14일
